package com.ailk.openbilling.service.imsintf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-12-07T13:34:37.366+05:45
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://imsintf.service.openbilling.ailk.com/", name = "IInfoMgntServiceWs")
@XmlSeeAlso({ObjectFactory.class})
public interface IInfoMgntServiceWs {

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_queryGroupInfo", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryGroupInfo")
    @WebMethod(operationName = "do_queryGroupInfo")
    @ResponseWrapper(localName = "do_queryGroupInfoResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryGroupInfoResponse")
    public com.ailk.openbilling.service.imsintf.DoQueryGroupInfoResponse2 doQueryGroupInfo(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sQueryGroupReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SQueryGroupReq sQueryGroupReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_queryWorkLog", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryWorkLog")
    @WebMethod(operationName = "do_queryWorkLog")
    @ResponseWrapper(localName = "do_queryWorkLogResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryWorkLogResponse")
    public com.ailk.openbilling.service.imsintf.DoQueryWorkLogResponse2 doQueryWorkLog(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "queryWorkLogReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.QueryWorkLogReq queryWorkLogReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_adjustBalance", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoAdjustBalance")
    @WebMethod(operationName = "do_adjustBalance")
    @ResponseWrapper(localName = "do_adjustBalanceResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoAdjustBalanceResponse")
    public com.ailk.openbilling.service.imsintf.DoAdjustBalanceResponse2 doAdjustBalance(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "adjustReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.AdjustBalanceReq adjustReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_querySharingPromotion", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQuerySharingPromotion")
    @WebMethod(operationName = "do_querySharingPromotion")
    @ResponseWrapper(localName = "do_querySharingPromotionResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQuerySharingPromotionResponse")
    public com.ailk.openbilling.service.imsintf.DoQuerySharingPromotionResponse2 doQuerySharingPromotion(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "querySharePromReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SQuerySharePromReq querySharePromReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_manageDeposit", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoManageDeposit")
    @WebMethod(operationName = "do_manageDeposit")
    @ResponseWrapper(localName = "do_manageDepositResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoManageDepositResponse")
    public com.ailk.openbilling.service.imsintf.DoSMngDepositResponse doManageDeposit(
        @WebParam(name = "oper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo oper,
        @WebParam(name = "req", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SMngDepositReq req
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_queryReguideInfo", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryReguideInfo")
    @WebMethod(operationName = "do_queryReguideInfo")
    @ResponseWrapper(localName = "do_queryReguideInfoResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryReguideInfoResponse")
    public com.ailk.openbilling.service.imsintf.DoQueryReguideInfoResp doQueryReguideInfo(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "queryReguideReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SQueryReguideReq queryReguideReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_autoTopUp", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoAutoTopUp")
    @WebMethod(operationName = "do_autoTopUp")
    @ResponseWrapper(localName = "do_autoTopUpResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoAutoTopUpResponse")
    public com.ailk.openbilling.service.imsintf.DoAutoTopUpResponse2 doAutoTopUp(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "autoTopUpReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SAutoTopUpReq autoTopUpReq,
        @WebParam(name = "oneTimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.OneTimeFee oneTimeFee
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_removeUser", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoRemoveUser")
    @WebMethod(operationName = "do_removeUser")
    @ResponseWrapper(localName = "do_removeUserResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoRemoveUserResponse")
    public com.ailk.openbilling.service.imsintf.DoRemoveUserResponse2 doRemoveUser(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sRemove", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SRemoveReq sRemove,
        @WebParam(name = "oneTimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.OneTimeFee oneTimeFee
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_changeMainPromotion", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoChangeMainPromotion")
    @WebMethod(operationName = "do_changeMainPromotion")
    @ResponseWrapper(localName = "do_changeMainPromotionResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoChangeMainPromotionResponse")
    public com.ailk.openbilling.service.imsintf.DoChangeProductResponse2 doChangeMainPromotion(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sChgProduct", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SChangeProduct sChgProduct,
        @WebParam(name = "oneTimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.OneTimeFee oneTimeFee
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_queryCapMax", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryCapMax")
    @WebMethod(operationName = "do_queryCapMax")
    @ResponseWrapper(localName = "do_queryCapMaxResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryCapMaxResponse")
    public com.ailk.openbilling.service.imsintf.DoQueryCapMaxResponse2 doQueryCapMax(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sQueryCapMaxReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SQueryCapMaxReq sQueryCapMaxReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_etopup", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoEtopup")
    @WebMethod(operationName = "do_etopup")
    @ResponseWrapper(localName = "do_etopupResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoEtopupResponse")
    public com.ailk.openbilling.service.imsintf.DoEtopupResponse2 doEtopup(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "etopupReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.EtopupReq etopupReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_changeGroupProducts", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoChangeGroupProducts")
    @WebMethod(operationName = "do_changeGroupProducts")
    @ResponseWrapper(localName = "do_changeGroupProductsResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoChangeGroupProductsResponse")
    public com.ailk.openbilling.service.imsintf.ChgGroupProductResp doChangeGroupProducts(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sChangeInfo", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.ChgGroupProduct sChangeInfo,
        @WebParam(name = "oneTimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.OneTimeFee oneTimeFee
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_oneTimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoOneTimeFee")
    @WebMethod(operationName = "do_oneTimeFee")
    @ResponseWrapper(localName = "do_oneTimeFeeResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoOneTimeFeeResponse")
    public com.ailk.openbilling.service.imsintf.DoOneTimeFeeResponse2 doOneTimeFee(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "oneTimeFeeList", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.OneTimeFeeList oneTimeFeeList
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_transfer", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoTransfer")
    @WebMethod(operationName = "do_transfer")
    @ResponseWrapper(localName = "do_transferResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoTransferResponse")
    public com.ailk.openbilling.service.imsintf.DoTransferResponse2 doTransfer(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sTransferReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.STransferReq sTransferReq,
        @WebParam(name = "oneTimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.OneTimeFee oneTimeFee
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_mailGroupManage", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoMailGroupManage")
    @WebMethod(operationName = "do_mailGroupManage")
    @ResponseWrapper(localName = "do_mailGroupManageResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoMailGroupManageResponse")
    public com.ailk.openbilling.service.imsintf.DoMailGroupManageResponse2 doMailGroupManage(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "mailGroupManageReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SMailGroupManageReq mailGroupManageReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_deleteGroup", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoDeleteGroup")
    @WebMethod(operationName = "do_deleteGroup")
    @ResponseWrapper(localName = "do_deleteGroupResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoDeleteGroupResponse")
    public com.ailk.openbilling.service.imsintf.DoDeleteGroupResponse2 doDeleteGroup(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sDeleteGroupReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SDeleteGroupReq sDeleteGroupReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_modifyCustBasicInfo", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoModifyCustBasicInfo")
    @WebMethod(operationName = "do_modifyCustBasicInfo")
    @ResponseWrapper(localName = "do_modifyCustBasicInfoResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoModifyCustBasicInfoResponse")
    public com.ailk.openbilling.service.imsintf.DoModifyCustBasicInfoResponse2 doModifyCustBasicInfo(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sCustomer", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SCustomer sCustomer,
        @WebParam(name = "sContactOperList", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SContactOperList sContactOperList
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_deductPoints", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoDeductPoints")
    @WebMethod(operationName = "do_deductPoints")
    @ResponseWrapper(localName = "do_deductPointsResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoDeductPointsResponse")
    public com.ailk.openbilling.service.imsintf.DoDeductPointsResponse2 doDeductPoints(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sDeductPointsReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SDeductPointsReq sDeductPointsReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_queryRecurringAndOnetimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryRecurringAndOnetimeFee")
    @WebMethod(operationName = "do_queryRecurringAndOnetimeFee")
    @ResponseWrapper(localName = "do_queryRecurringAndOnetimeFeeResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryRecurringAndOnetimeFeeResponse")
    public com.ailk.openbilling.service.imsintf.DoQueryRecurringfeeOnetimefeeResp doQueryRecurringAndOnetimeFee(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "queryRecurringFeeReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SQueryRecurringAndOnetimeFeeReq queryRecurringFeeReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_caRelation", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoCaRelation")
    @WebMethod(operationName = "do_caRelation")
    @ResponseWrapper(localName = "do_caRelationResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoCaRelationResponse")
    public com.ailk.openbilling.service.imsintf.DoCaRelationResponse2 doCaRelation(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sCARelationReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.ScaRelateReq sCARelationReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_queryMaxFreeResource", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryMaxFreeResource")
    @WebMethod(operationName = "do_queryMaxFreeResource")
    @ResponseWrapper(localName = "do_queryMaxFreeResourceResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryMaxFreeResourceResponse")
    public com.ailk.openbilling.service.imsintf.DoQueryMaxFreeResourceResponse2 doQueryMaxFreeResource(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "queryMaxFreeResourceReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SQueryMaxFreeResourceReq queryMaxFreeResourceReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_cancelTopUp", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoCancelTopUp")
    @WebMethod(operationName = "do_cancelTopUp")
    @ResponseWrapper(localName = "do_cancelTopUpResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoCancelTopUpResponse")
    public com.ailk.openbilling.service.imsintf.DoCancelTopUpResponse2 doCancelTopUp(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "scancelTopUp", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SCancelTopUpReq scancelTopUp
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_changePaymentMode", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoChangePaymentMode")
    @WebMethod(operationName = "do_changePaymentMode")
    @ResponseWrapper(localName = "do_changePaymentModeResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoChangePaymentModeResponse")
    public com.ailk.openbilling.service.imsintf.DoChangePaymentModeResponse2 doChangePaymentMode(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sChangePaymentMode", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SChangePaymentModeReq sChangePaymentMode,
        @WebParam(name = "oneTimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.OneTimeFee oneTimeFee
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_renewRegistration", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoRenewRegistration")
    @WebMethod(operationName = "do_renewRegistration")
    @ResponseWrapper(localName = "do_renewRegistrationResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoRenewRegistrationResponse")
    public com.ailk.openbilling.service.imsintf.DoRenewRegistrationResponse2 doRenewRegistration(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sRenew", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.RenewRegistration sRenew
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_setNegativeBalance", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoSetNegativeBalance")
    @WebMethod(operationName = "do_setNegativeBalance")
    @ResponseWrapper(localName = "do_setNegativeBalanceResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoSetNegativeBalanceResponse")
    public com.ailk.openbilling.service.imsintf.DoSetNegativeBalanceResponse2 doSetNegativeBalance(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "ssetNegativeBalanceReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SSetNegativeBalanceReq ssetNegativeBalanceReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_deactivateGroup", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoDeactivateGroup")
    @WebMethod(operationName = "do_deactivateGroup")
    @ResponseWrapper(localName = "do_deactivateGroupResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoDeactivateGroupResponse")
    public com.ailk.openbilling.service.imsintf.DoDeactivateGroupResponse2 doDeactivateGroup(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sDeactivateGroupReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SDeactivateGroupReq sDeactivateGroupReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_oneTimeFeeDelayCharge", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoOneTimeFeeDelayCharge")
    @WebMethod(operationName = "do_oneTimeFeeDelayCharge")
    @ResponseWrapper(localName = "do_oneTimeFeeDelayChargeResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoOneTimeFeeDelayChargeResponse")
    public com.ailk.openbilling.service.imsintf.DoOneTimeFeeResponse2 doOneTimeFeeDelayCharge(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "oneTimeFeeList", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.OneTimeFeeList oneTimeFeeList
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_caRelationUser", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoCaRelationUser")
    @WebMethod(operationName = "do_caRelationUser")
    @ResponseWrapper(localName = "do_caRelationUserResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoCaRelationUserResponse")
    public com.ailk.openbilling.service.imsintf.DoCaRelationUserResponse2 doCaRelationUser(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sCARelationUserReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.ScaRelateUserReq sCARelationUserReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_query", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQuery")
    @WebMethod(operationName = "do_query")
    @ResponseWrapper(localName = "do_queryResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryResponse")
    public com.ailk.openbilling.service.imsintf.DoQueryResponse2 doQuery(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "queryTypeList", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.QueryTypeList queryTypeList,
        @WebParam(name = "queryParam", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SQueryParam queryParam
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_cancelOneTimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoCancelOneTimeFee")
    @WebMethod(operationName = "do_cancelOneTimeFee")
    @ResponseWrapper(localName = "do_cancelOneTimeFeeResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoCancelOneTimeFeeResponse")
    public com.ailk.openbilling.service.imsintf.DoCancelOneTimeFeeResponse2 doCancelOneTimeFee(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sCancelOneTimeFeeReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SCancelOneTimeFeeReq sCancelOneTimeFeeReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_setBudget", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoSetBudget")
    @WebMethod(operationName = "do_setBudget")
    @ResponseWrapper(localName = "do_setBudgetResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoSetBudgetResponse")
    public com.ailk.openbilling.service.imsintf.DoSetBudgetResponse2 doSetBudget(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sSetBudget", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SSetBudgetReq sSetBudget
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_hotBill", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoHotBill")
    @WebMethod(operationName = "do_hotBill")
    @ResponseWrapper(localName = "do_hotBillResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoHotBillResponse")
    public com.ailk.openbilling.service.imsintf.DoHotBillResponse2 doHotBill(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sHotBillReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SHotBillReq sHotBillReq,
        @WebParam(name = "oneTimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.OneTimeFee oneTimeFee
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_queryNotifyHis", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryNotifyHis")
    @WebMethod(operationName = "do_queryNotifyHis")
    @ResponseWrapper(localName = "do_queryNotifyHisResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryNotifyHisResponse")
    public com.ailk.openbilling.service.imsintf.DoQueryNotifyHisResponse2 doQueryNotifyHis(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "req", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SQueryNotificationHisReq req
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_queryBusiSuccess", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryBusiSuccess")
    @WebMethod(operationName = "do_queryBusiSuccess")
    @ResponseWrapper(localName = "do_queryBusiSuccessResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryBusiSuccessResponse")
    public com.ailk.openbilling.service.imsintf.DoQueryBusiSuccessResponse2 doQueryBusiSuccess(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "qryBusiSuccess", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.QueryBusiSuccessReq qryBusiSuccess
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_queryUsersByBssbroker", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryUsersByBssbroker")
    @WebMethod(operationName = "do_queryUsersByBssbroker")
    @ResponseWrapper(localName = "do_queryUsersByBssbrokerResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryUsersByBssbrokerResponse")
    public com.ailk.openbilling.service.imsintf.DoQueryUsersByBssResponse doQueryUsersByBssbroker(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sQueryUsersByBssReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SQueryUsersByBssReq sQueryUsersByBssReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_mgntCallScreen", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoMgntCallScreen")
    @WebMethod(operationName = "do_mgntCallScreen")
    @ResponseWrapper(localName = "do_mgntCallScreenResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoMgntCallScreenResponse")
    public com.ailk.openbilling.service.imsintf.DoMgntCallScreenResponse2 doMgntCallScreen(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sCallScreenReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SMgntCallScreenReq sCallScreenReq,
        @WebParam(name = "oneTimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.OneTimeFee oneTimeFee
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_changeMsisdnAndSim", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoChangeMsisdnAndSim")
    @WebMethod(operationName = "do_changeMsisdnAndSim")
    @ResponseWrapper(localName = "do_changeMsisdnAndSimResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoChangeMsisdnAndSimResponse")
    public com.ailk.openbilling.service.imsintf.DoChangeMsisdnAndSimResponse2 doChangeMsisdnAndSim(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "changeInfo", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.ChangeMsisdnAndSimInfo changeInfo,
        @WebParam(name = "oneTimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.OneTimeFee oneTimeFee
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_changeOwnerReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoChangeOwnerReq")
    @WebMethod(operationName = "do_changeOwnerReq")
    @ResponseWrapper(localName = "do_changeOwnerReqResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoChangeOwnerReqResponse")
    public com.ailk.openbilling.service.imsintf.DoChangeOwnerReqResponse2 doChangeOwnerReq(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sChangeOwner", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SChangeOwnerReq sChangeOwner,
        @WebParam(name = "oneTimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.OneTimeFee oneTimeFee
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_topUpByCash", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoTopUpByCash")
    @WebMethod(operationName = "do_topUpByCash")
    @ResponseWrapper(localName = "do_topUpByCashResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoTopUpByCashResponse")
    public com.ailk.openbilling.service.imsintf.DoTopUpByCashResponse2 doTopUpByCash(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sTopUpInfo", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.STopUpInfo sTopUpInfo
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_modifyAccountState", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoModifyAccountState")
    @WebMethod(operationName = "do_modifyAccountState")
    @ResponseWrapper(localName = "do_modifyAccountStateResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoModifyAccountStateResponse")
    public com.ailk.openbilling.service.imsintf.DoModifyAccountStateResponse2 doModifyAccountState(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sModifyAcctReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.ModifyAcctReq sModifyAcctReq,
        @WebParam(name = "sOneTimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.OneTimeFee sOneTimeFee
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_advancePayment", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoAdvancePayment")
    @WebMethod(operationName = "do_advancePayment")
    @ResponseWrapper(localName = "do_advancePaymentResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoAdvancePaymentResponse")
    public com.ailk.openbilling.service.imsintf.DoAdvancePaymentResponse2 doAdvancePayment(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "advancePaymentReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.AdvancePaymentReq advancePaymentReq,
        @WebParam(name = "notification_flag", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        java.lang.Short notificationFlag
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_setCreditLimit", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoSetCreditLimit")
    @WebMethod(operationName = "do_setCreditLimit")
    @ResponseWrapper(localName = "do_setCreditLimitResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoSetCreditLimitResponse")
    public com.ailk.openbilling.service.imsintf.DoSetCreditLimitResponse2 doSetCreditLimit(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "SSetCreditLimit", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SSetCreditLimitReq sSetCreditLimit
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_setNotificationFlag", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoSetNotificationFlag")
    @WebMethod(operationName = "do_setNotificationFlag")
    @ResponseWrapper(localName = "do_setNotificationFlagResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoSetNotificationFlagResponse")
    public com.ailk.openbilling.service.imsintf.DoSetNotificationFlagResponse2 doSetNotificationFlag(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "ssetNotificationReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SSetNotificationFlagReq ssetNotificationReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_queryProdState", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryProdState")
    @WebMethod(operationName = "do_queryProdState")
    @ResponseWrapper(localName = "do_queryProdStateResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryProdStateResponse")
    public com.ailk.openbilling.service.imsintf.DoQueryProdStateResponse2 doQueryProdState(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "req", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SQueryProdState req
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_bankConfiguration", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoBankConfiguration")
    @WebMethod(operationName = "do_bankConfiguration")
    @ResponseWrapper(localName = "do_bankConfigurationResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoBankConfigurationResponse")
    public com.ailk.openbilling.service.imsintf.DoBankConfigurationResponse2 doBankConfiguration(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "bankInfo", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.BankInfo bankInfo,
        @WebParam(name = "oper_type", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        java.lang.Short operType
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_gsmTopUp", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoGsmTopUp")
    @WebMethod(operationName = "do_gsmTopUp")
    @ResponseWrapper(localName = "do_gsmTopUpResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoGsmTopUpResponse")
    public com.ailk.openbilling.service.imsintf.DoGsmTopUpResponse2 doGsmTopUp(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "gsmTopUp", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SGsmTopUpReq gsmTopUp
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_queryDeposit", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryDeposit")
    @WebMethod(operationName = "do_queryDeposit")
    @ResponseWrapper(localName = "do_queryDepositResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryDepositResponse")
    public com.ailk.openbilling.service.imsintf.DoSMngQueryDepositResponse doQueryDeposit(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "req", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SMngQueryDepositReq req
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_deletePrematch", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoDeletePrematch")
    @WebMethod(operationName = "do_deletePrematch")
    @ResponseWrapper(localName = "do_deletePrematchResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoDeletePrematchResponse")
    public com.ailk.openbilling.service.imsintf.DoDeletePrematchResponse2 doDeletePrematch(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sDeletePrematchReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SDeletePrematchReq sDeletePrematchReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_queryBillingStatus", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryBillingStatus")
    @WebMethod(operationName = "do_queryBillingStatus")
    @ResponseWrapper(localName = "do_queryBillingStatusResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryBillingStatusResponse")
    public com.ailk.openbilling.service.imsintf.DoQueryBillingStatusResponse2 doQueryBillingStatus(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "qryBillStsReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SQryBillStsReq qryBillStsReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_queryGroupMembers", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryGroupMembers")
    @WebMethod(operationName = "do_queryGroupMembers")
    @ResponseWrapper(localName = "do_queryGroupMembersResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryGroupMembersResponse")
    public com.ailk.openbilling.service.imsintf.DoQueryGroupMembersResponse2 doQueryGroupMembers(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "queryGroupMembersReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.QueryGroupMembersReq queryGroupMembersReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_lifeCycleMgnt", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoLifeCycleMgnt")
    @WebMethod(operationName = "do_lifeCycleMgnt")
    @ResponseWrapper(localName = "do_lifeCycleMgntResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoLifeCycleMgntResponse")
    public com.ailk.openbilling.service.imsintf.DoLifeCycleMgntResponse2 doLifeCycleMgnt(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sLifeCycle", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SUserStatus sLifeCycle,
        @WebParam(name = "oneTimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.OneTimeFee oneTimeFee
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_changeProduct", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoChangeProduct")
    @WebMethod(operationName = "do_changeProduct")
    @ResponseWrapper(localName = "do_changeProductResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoChangeProductResponse")
    public com.ailk.openbilling.service.imsintf.DoChangeProductResponse2 doChangeProduct(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sChgProduct", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SChangeProduct sChgProduct,
        @WebParam(name = "oneTimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.OneTimeFee oneTimeFee
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_mgntCRMBlackList", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoMgntCRMBlackList")
    @WebMethod(operationName = "do_mgntCRMBlackList")
    @ResponseWrapper(localName = "do_mgntCRMBlackListResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoMgntCRMBlackListResponse")
    public com.ailk.openbilling.service.imsintf.DoMgntCRMBlackListResponse2 doMgntCRMBlackList(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "smgntCRMBlackListReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SMgntCRMBlackListReq smgntCRMBlackListReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_queryServiceState", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryServiceState")
    @WebMethod(operationName = "do_queryServiceState")
    @ResponseWrapper(localName = "do_queryServiceStateResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryServiceStateResponse")
    public com.ailk.openbilling.service.imsintf.DoQueryServiceStateResponse2 doQueryServiceState(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "req", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SQuerySrvStateReq req
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_reguide", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoReguide")
    @WebMethod(operationName = "do_reguide")
    @ResponseWrapper(localName = "do_reguideResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoReguideResponse")
    public com.ailk.openbilling.service.imsintf.DoReguideMgntResponse doReguide(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sRelationReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SUserPayReguideRelList sRelationReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_changeUserLanguage", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoChangeUserLanguage")
    @WebMethod(operationName = "do_changeUserLanguage")
    @ResponseWrapper(localName = "do_changeUserLanguageResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoChangeUserLanguageResponse")
    public com.ailk.openbilling.service.imsintf.DoChangeUserLanguageResponse2 doChangeUserLanguage(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "changeUserLanguageReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.ChangeUserLanguageReq changeUserLanguageReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_cancelOrder", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoCancelOrder")
    @WebMethod(operationName = "do_cancelOrder")
    @ResponseWrapper(localName = "do_cancelOrderResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoCancelOrderResponse")
    public com.ailk.openbilling.service.imsintf.DoCancelOrderResponse2 doCancelOrder(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "cancelOrderInfo", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.CancelOrderInfo cancelOrderInfo
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_queryMemberInfo", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryMemberInfo")
    @WebMethod(operationName = "do_queryMemberInfo")
    @ResponseWrapper(localName = "do_queryMemberInfoResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryMemberInfoResponse")
    public com.ailk.openbilling.service.imsintf.DoQueryMemberInfoResponse2 doQueryMemberInfo(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sQueryGroupMemberReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SQueryGroupMemberReq sQueryGroupMemberReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_split", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoSplit")
    @WebMethod(operationName = "do_split")
    @ResponseWrapper(localName = "do_splitResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoSplitResponse")
    public com.ailk.openbilling.service.imsintf.DoSplitResponse2 doSplit(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "relationReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SUserPaySplitRelList relationReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_modifyProductState", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoModifyProductState")
    @WebMethod(operationName = "do_modifyProductState")
    @ResponseWrapper(localName = "do_modifyProductStateResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoModifyProductStateResponse")
    public com.ailk.openbilling.service.imsintf.DoModifyProductStateResponse2 doModifyProductState(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sChangeInfo", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.ModifyProductState sChangeInfo,
        @WebParam(name = "sOneTimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.OneTimeFee sOneTimeFee
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_vpnGroupRelation", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoVpnGroupRelation")
    @WebMethod(operationName = "do_vpnGroupRelation")
    @ResponseWrapper(localName = "do_vpnGroupRelationResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoVpnGroupRelationResponse")
    public com.ailk.openbilling.service.imsintf.DoVPNGroupRelationResponse2 doVpnGroupRelation(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "SVPNRelationReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SvpnRelationReq svpnRelationReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_querySuppressNotification", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQuerySuppressNotification")
    @WebMethod(operationName = "do_querySuppressNotification")
    @ResponseWrapper(localName = "do_querySuppressNotificationResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQuerySuppressNotificationResponse")
    public com.ailk.openbilling.service.imsintf.DoQuerySuppressNotificationResponse2 doQuerySuppressNotification(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "querySuppressNotificationReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SQuerySuppressNotificationReq querySuppressNotificationReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_mgntGroupMember", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoMgntGroupMember")
    @WebMethod(operationName = "do_mgntGroupMember")
    @ResponseWrapper(localName = "do_mgntGroupMemberResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoMgntGroupMemberResponse")
    public com.ailk.openbilling.service.imsintf.DoMgntGroupMemberResponse2 doMgntGroupMember(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sMngGroupMemberReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SMgnGroupMemberReq sMngGroupMemberReq,
        @WebParam(name = "oneTimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.OneTimeFee oneTimeFee
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_queryGraph", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryGraph")
    @WebMethod(operationName = "do_queryGraph")
    @ResponseWrapper(localName = "do_queryGraphResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryGraphResponse")
    public com.ailk.openbilling.service.imsintf.DoQueryGraphResponse2 doQueryGraph(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "req", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SQueryGraphReq req
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_firstActivation", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoFirstActivation")
    @WebMethod(operationName = "do_firstActivation")
    @ResponseWrapper(localName = "do_firstActivationResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoFirstActivationResponse")
    public com.ailk.openbilling.service.imsintf.DoFirstActivationResponse2 doFirstActivation(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sFristActiveReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SFristActiveReq sFristActiveReq,
        @WebParam(name = "oneTimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.OneTimeFee oneTimeFee
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_manageMultiSim", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoManageMultiSim")
    @WebMethod(operationName = "do_manageMultiSim")
    @ResponseWrapper(localName = "do_manageMultiSimResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoManageMultiSimResponse")
    public com.ailk.openbilling.service.imsintf.DoOperateMultiSimResponse doManageMultiSim(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sOperateMultiSimReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperateMultiSimReq sOperateMultiSimReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_queryFN", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryFN")
    @WebMethod(operationName = "do_queryFN")
    @ResponseWrapper(localName = "do_queryFNResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryFNResponse")
    public com.ailk.openbilling.service.imsintf.DoQueryFNResponse2 doQueryFN(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "queryFnReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.QueryFnReq queryFnReq,
        @WebParam(name = "oneTimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.OneTimeFee oneTimeFee
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_queryScpProfile", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryScpProfile")
    @WebMethod(operationName = "do_queryScpProfile")
    @ResponseWrapper(localName = "do_queryScpProfileResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryScpProfileResponse")
    public com.ailk.openbilling.service.imsintf.DoQueryScpProfileResponse2 doQueryScpProfile(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "scpProfileReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.ScpProfileReq scpProfileReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_setExemptCreditLimit", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoSetExemptCreditLimit")
    @WebMethod(operationName = "do_setExemptCreditLimit")
    @ResponseWrapper(localName = "do_setExemptCreditLimitResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoSetExemptCreditLimitResponse")
    public com.ailk.openbilling.service.imsintf.DoSetExemptCreditLimitResponse2 doSetExemptCreditLimit(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "setExemptLimitReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SSetEmptLimitReq setExemptLimitReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_cancelPayment", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoCancelPayment")
    @WebMethod(operationName = "do_cancelPayment")
    @ResponseWrapper(localName = "do_cancelPaymentResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoCancelPaymentResponse")
    public com.ailk.openbilling.service.imsintf.DoCancelPaymentResponse2 doCancelPayment(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "CancelPaymentInfo", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.CancelPaymentInfo cancelPaymentInfo
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_adjustBill", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoAdjustBill")
    @WebMethod(operationName = "do_adjustBill")
    @ResponseWrapper(localName = "do_adjustBillResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoAdjustBillResponse")
    public com.ailk.openbilling.service.imsintf.DoAdjustBillResponse2 doAdjustBill(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "adjust_type", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        java.lang.Short adjustType,
        @WebParam(name = "billInfo", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.Billinfo billInfo,
        @WebParam(name = "notification_flag", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        java.lang.Short notificationFlag
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_changeBillCycle", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoChangeBillCycle")
    @WebMethod(operationName = "do_changeBillCycle")
    @ResponseWrapper(localName = "do_changeBillCycleResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoChangeBillCycleResponse")
    public com.ailk.openbilling.service.imsintf.DoChangeBillCycleResponse2 doChangeBillCycle(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sChgBillCycleReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SChgBillCycleReq sChgBillCycleReq,
        @WebParam(name = "old_bill_cycle", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SBillCycle oldBillCycle,
        @WebParam(name = "new_bill_cycle", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SBillCycle newBillCycle,
        @WebParam(name = "oneTimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.OneTimeFee oneTimeFee
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_queryLostBalance", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryLostBalance")
    @WebMethod(operationName = "do_queryLostBalance")
    @ResponseWrapper(localName = "do_queryLostBalanceResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryLostBalanceResponse")
    public com.ailk.openbilling.service.imsintf.DoQueryLostBalanceResponce doQueryLostBalance(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "queryLostBalanceReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.DoQueryLostBalanceReq queryLostBalanceReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_newRegistration", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoNewRegistration")
    @WebMethod(operationName = "do_newRegistration")
    @ResponseWrapper(localName = "do_newRegistrationResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoNewRegistrationResponse")
    public com.ailk.openbilling.service.imsintf.DoNewRegistrationResponse2 doNewRegistration(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "newRegistration", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.NewRegistration newRegistration,
        @WebParam(name = "flag", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        java.lang.Short flag,
        @WebParam(name = "oneTimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.OneTimeFee oneTimeFee
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_manageUserFriendsNums", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoManageUserFriendsNums")
    @WebMethod(operationName = "do_manageUserFriendsNums")
    @ResponseWrapper(localName = "do_manageUserFriendsNumsResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoManageUserFriendsNumsResponse")
    public com.ailk.openbilling.service.imsintf.DoManageUserFriendsNumsResponse2 doManageUserFriendsNums(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sMangeUserFNs", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.ManageUserFriendsNum sMangeUserFNs,
        @WebParam(name = "oneTimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.OneTimeFee oneTimeFee
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_dismissReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoDismissReq")
    @WebMethod(operationName = "do_dismissReq")
    @ResponseWrapper(localName = "do_dismissReqResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoDismissReqResponse")
    public com.ailk.openbilling.service.imsintf.DoDismissReqResponse2 doDismissReq(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sDismissReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SDismissReq sDismissReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_changeGroup", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoChangeGroup")
    @WebMethod(operationName = "do_changeGroup")
    @ResponseWrapper(localName = "do_changeGroupResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoChangeGroupResponse")
    public com.ailk.openbilling.service.imsintf.DoChangeGroupResponse2 doChangeGroup(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sGroup", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SGroup sGroup
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_manageIRParty", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoManageIRParty")
    @WebMethod(operationName = "do_manageIRParty")
    @ResponseWrapper(localName = "do_manageIRPartyResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoManageIRPartyResponse")
    public com.ailk.openbilling.service.imsintf.DoManageIRPartyResponse2 doManageIRParty(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sManageIRParty", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SManagerIRPartyReq sManageIRParty
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_authParent", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoAuthParent")
    @WebMethod(operationName = "do_authParent")
    @ResponseWrapper(localName = "do_authParentResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoAuthParentResponse")
    public com.ailk.openbilling.service.imsintf.DoAuthParentResponse2 doAuthParent(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sAuthReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SAuthParentReq sAuthReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_modifyAccountBasicInfo", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoModifyAccountBasicInfo")
    @WebMethod(operationName = "do_modifyAccountBasicInfo")
    @ResponseWrapper(localName = "do_modifyAccountBasicInfoResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoModifyAccountBasicInfoResponse")
    public com.ailk.openbilling.service.imsintf.DoModifyAccountBasicInfoResponse2 doModifyAccountBasicInfo(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sAccount", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SAccount sAccount,
        @WebParam(name = "sContactOperList", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SContactOperList sContactOperList
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_setMaxFreeResource", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoSetMaxFreeResource")
    @WebMethod(operationName = "do_setMaxFreeResource")
    @ResponseWrapper(localName = "do_setMaxFreeResourceResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoSetMaxFreeResourceResponse")
    public com.ailk.openbilling.service.imsintf.DoSetMaxFreeResourceResponse2 doSetMaxFreeResource(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "maxFreeResourceReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.MaxFreeResourceReq maxFreeResourceReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_queryInvoiceInfo", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryInvoiceInfo")
    @WebMethod(operationName = "do_queryInvoiceInfo")
    @ResponseWrapper(localName = "do_queryInvoiceInfoResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryInvoiceInfoResponse")
    public com.ailk.openbilling.service.imsintf.DoQueryInvoiceInfoResponse2 doQueryInvoiceInfo(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sQueryInvoiceInfoReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SQueryInvoiceInfoReq sQueryInvoiceInfoReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_deactivateGroupMem", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoDeactivateGroupMem")
    @WebMethod(operationName = "do_deactivateGroupMem")
    @ResponseWrapper(localName = "do_deactivateGroupMemResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoDeactivateGroupMemResponse")
    public com.ailk.openbilling.service.imsintf.DoDeactivateGroupMemResponse2 doDeactivateGroupMem(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sDeactivateGroupMemReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SDeactivateGroupMemReq sDeactivateGroupMemReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_modifyUserBasicInfo", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoModifyUserBasicInfo")
    @WebMethod(operationName = "do_modifyUserBasicInfo")
    @ResponseWrapper(localName = "do_modifyUserBasicInfoResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoModifyUserBasicInfoResponse")
    public com.ailk.openbilling.service.imsintf.DoModifyUserBasicInfoResponse2 doModifyUserBasicInfo(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sUser", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SUser sUser
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_cancelGsmTopUp", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoCancelGsmTopUp")
    @WebMethod(operationName = "do_cancelGsmTopUp")
    @ResponseWrapper(localName = "do_cancelGsmTopUpResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoCancelGsmTopUpResponse")
    public com.ailk.openbilling.service.imsintf.DoCancelGsmTopUpResponse2 doCancelGsmTopUp(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "gsmTopUp", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SCancelGsmTopUpReq gsmTopUp
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_queryCallScreen", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryCallScreen")
    @WebMethod(operationName = "do_queryCallScreen")
    @ResponseWrapper(localName = "do_queryCallScreenResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryCallScreenResponse")
    public com.ailk.openbilling.service.imsintf.DoQueryCallScreenResponse2 doQueryCallScreen(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "queryCallScreenReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.QueryCallScreenReq queryCallScreenReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_resetNegativeValue", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoResetNegativeValue")
    @WebMethod(operationName = "do_resetNegativeValue")
    @ResponseWrapper(localName = "do_resetNegativeValueResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoResetNegativeValueResponse")
    public com.ailk.openbilling.service.imsintf.DoResetNegativeValueResponse2 doResetNegativeValue(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "resetNegativeValueReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SResetNegativeValueReq resetNegativeValueReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_paymentAndBillAdjust", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoPaymentAndBillAdjust")
    @WebMethod(operationName = "do_paymentAndBillAdjust")
    @ResponseWrapper(localName = "do_paymentAndBillAdjustResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoPaymentAndBillAdjustResponse")
    public com.ailk.openbilling.service.imsintf.DoPaymentAndBillAdjustResponse2 doPaymentAndBillAdjust(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "spaymentReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SPaymentReq spaymentReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_queryCDR", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryCDR")
    @WebMethod(operationName = "do_queryCDR")
    @ResponseWrapper(localName = "do_queryCDRResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoQueryCDRResponse")
    public com.ailk.openbilling.service.imsintf.DoQueryCDRResponse2 doQueryCDR(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sQueryCDRReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SQueryCDRReq sQueryCDRReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_mgntScpProfile", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoMgntScpProfile")
    @WebMethod(operationName = "do_mgntScpProfile")
    @ResponseWrapper(localName = "do_mgntScpProfileResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoMgntScpProfileResponse")
    public com.ailk.openbilling.service.imsintf.DoMgntScpProfileResponse2 doMgntScpProfile(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "scpProfileInfo", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.ScpProfileInfo scpProfileInfo,
        @WebParam(name = "sUserAuth", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SUserAuth sUserAuth,
        @WebParam(name = "oneTimeFee", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.OneTimeFee oneTimeFee
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_changeGroupInfo", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoChangeGroupInfo")
    @WebMethod(operationName = "do_changeGroupInfo")
    @ResponseWrapper(localName = "do_changeGroupInfoResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoChangeGroupInfoResponse")
    public com.ailk.openbilling.service.imsintf.DoChangeGroupInfoResponse2 doChangeGroupInfo(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "changeGroupInfoReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SChangeGroupInfoReq changeGroupInfoReq
    );

    @WebResult(name = "return", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
    @RequestWrapper(localName = "do_newGroupReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoNewGroupReq")
    @WebMethod(operationName = "do_newGroupReq")
    @ResponseWrapper(localName = "do_newGroupReqResponse", targetNamespace = "http://imsintf.service.openbilling.ailk.com/", className = "com.ailk.openbilling.service.imsintf.DoNewGroupReqResponse")
    public com.ailk.openbilling.service.imsintf.DoNewGroupReqResponse2 doNewGroupReq(
        @WebParam(name = "sOper", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SOperInfo sOper,
        @WebParam(name = "sNewGroupReq", targetNamespace = "http://imsintf.service.openbilling.ailk.com/")
        com.ailk.openbilling.service.imsintf.SNewGroupReq sNewGroupReq
    );
}
